title: Pink Banana's Blog
description: A mind palace for myself
name: Crazy Phage
markdown: redcarpet
encoding: "utf-8"
permalink: blog/:year/:month/:day/:title.html

# --using code highlighting on github and linux
highlighter: pygments

# --using code highlighting on windows
# pygments: false
# highlighter: rouge

extensions: [fenced_code_blocks]
rss_path: feed.xml
BASE_PATH: http://lostpupil.github.io
img_url: /images

comments :
  provider : uyan
